version: '3'
services:
  strapi:
    image: strapi/strapi:latest
    ports:
      - 1337:1337
    volumes:
      - /home/docker-data/strapi:/srv/app
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: $DB_NAME
      DATABASE_USERNAME: $DB_USER
      DATABASE_PASSWORD: $DB_USER_PASS
      DATABASE_SSL: 'false'
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/docker-data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_USER_PASS
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network: